### ISSUE TITLE
why use  '__atomic_load_n'  to get   ‘ring_buffer->max_read_cursor.sequence’  ?

### ISSUE THREAD

**Issue by huoyingyangjie** [colding/disruptorC#5]
Hi
I have some questions.Why not use   ‘ring_buffer->max_read_cursor.sequence’   directly?

**Comment by colding** [comment]
Because I am then guaranteed that the sequence number is read atomically. Some (most? all?) CPUs will do that anyways, but I'd just rather be safe than sorry.
